name: lecapi
recipe: drupal9
config:
  webroot: web
  # Off by default for performance. Set to `true` and run `lando rebuild` (will not reset database).
  xdebug: true
keys:
  - id_rsa
tooling:
  drush:
    # Override .lando.upstream.yml
    service: appserver
  # @see docs/backend.md.
  sync-prod:
    service: appserver
    description: Syncs prod database and files to local.
    cmd:
      - drush sql:drop
      - drush sql:sync @prod @self --yes
      - drush cache:rebuild
      - drush user:login
  theme-build:
    service: node
    description: Build the theme.
    dir: /app/web/themes/custom/legin
    cmd: npm install
  theme-watch:
    service: node
    description: Watch the theme.
    dir: /app/web/themes/custom/legin
    cmd: gulp
  theme-generate:
    service: node
    description: Watch the theme.
    dir: /app/web/themes/custom/legin
    cmd: gulp sass
services:
  solr:
    type: solr:7.7
    portforward: true
    core: drupal
    config:
      dir: .platform/configsets/solr7
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  node:
    type: node
    globals:
      gulp-cli: latest
