<?php

/**
 * @file
 * ...
 */

use Drupal\Core\Entity\EntityForm;
use Drupal\Core\Form\FormStateInterface;
use Drupal\model\Model\NodeGeneric;
use Drupal\model\Model\Node\NodeArticle;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function model_entity_bundle_info_alter(&$bundles) {
  $bundles['node']['article']['class'] = NodeArticle::class;
  $bundles['node']['page']['class'] = NodeGeneric::class;
  $bundles['node']['event']['class'] = NodeGeneric::class;
}

/**
 * Implements hook_form_alter().
 */
function model_form_alter(array &$form, FormStateInterface $form_state): void {
  // If a bundle class exists, check if it wants to alter its form.
  if ($form_state->getFormObject() instanceof EntityForm) {
    $entity = $form_state->getFormObject()->getEntity();
    if (method_exists($entity, 'formAlter')) {
      $entity->formAlter($form, $form_state);
    }
  }
}
