<?php

/**
 * @file
 * Main theme file.
 */

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function legin_theme_suggestions_container_alter(array &$suggestions, array &$variables) {

  // Overriding this so that it's obvious to a themer who is inspecting templates that we're playing in this space.
  if (isset($variables['element']['#paragraph_type'])) {
    array_unshift($suggestions, 'container__paragraphs_subform');
  }

}
